#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-1  -d I II III IV V VI VII VIII IX X
bspc monitor  -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#xrandr --output HDMI-1 --primary


sxhkd &
picom &
#polybar &./../../../Recursos/images/
feh --bg-scale ~/.dotfile/Recursos/image/girlProgramming.png &
kitty --hold neofetch &
kitty --hold cmatrix &
kitty --hold htop &
